### ISSUE TITLE
Can't use atsign-micropython custom built releases in old Linux versions due to a package version mismatch

### ISSUE THREAD

**Issue by realvarx** [atsign-foundation/at_pico_w#20]
- It is possible to manually compile the coverage variant of micropython in older Linux versions (such as Debian 10). It will execute and allow the user to run files. However, it wont do it properly:
```
astt@as2019:~/Escritorio/at_pico_w/src$ micropython
MicroPython v1.20.0-161-gdb5444f68 on 2023-06-06; linux [GCC 8.3.0] version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> 
astt@as2019:~/Escritorio/at_pico_w/src$ micropython main.py
linux
Traceback (most recent call last):
  File "main.py", line 9, in <module>
  File "./lib/atclient.py", line 8, in <module>
  File "./lib/third_party/rsa/__init__.py", line 27, in <module>
  File "./lib/third_party/rsa/key.py", line 572, in <module>
AttributeError: 'module' object has no attribute 'rsa'
astt@as2019:~/Escritorio/at_pico_w/src$ 
```
This probably happens due to a mismatch in the `libffi` library (atsign-micropython is compiled using `libffi7`, while some older Linux versions will compile it with `libffi6`).
This is what happens when I try to run atsign-micropython in Debian 10:
```
astt@as2019:~/Escritorio/at_pico_w/src$ ~/Escritorio/test-upy/micropython_1.19.1_63a59ee4e/micropython main.py
/home/astt/Escritorio/test-upy/micropython_1.19.1_63a59ee4e/micropython: error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory
```
And here we can see the `libffi` version:
```
astt@as2019:~/Escritorio/at_pico_w/src$ apt-cache search libffi
libffindex0 - library for simple index/database for huge amounts of small files
libffindex0-dev - library for simple index/database for huge amounts of small files (development)
libjffi-java - Java Foreign Function Interface
libjffi-jni - Java Foreign Function Interface (JNI library)
libalt-alien-ffi-system-perl - simplified alternative to Alien::FFI that uses system libffi
libffi-dev - Foreign Function Interface library (development files)
libffi6 - Foreign Function Interface library runtime
libffi6-dbg - Foreign Function Interface library runtime (debug symbols)
libffi-checklib-perl - module to check availability of a library for FFI
libffi-platypus-perl - module to create Perl bindings to non-Perl libraries with FFI
```

- Same code works fine when executed using atsign-micropython in a more recent Linux (Ubuntu 20.04.3 LTS):
```
realvarx@rs-2022:~/Desktop/at_pico_w/src$ micropython main.py
Welcome! What would you like to do?
	1) Set recipient atSign (presently cpswan)
	2) Connect to arrogantcheetah
	3) Send at atTalk message to cpswan
	4) Exit
> 
```

**Comment by cpswan** [comment]
@realvarx can you please try the latest binaries in the [1.20.0_3faded33f_AES_CTR](https://github.com/atsign-foundation/micropython/releases/tag/1.20.0_3faded33f_AES_CTR) release.

**Comment by realvarx** [comment]
@cpswan Looks like the actual problem could be related to updates of MicroPython itself, rather than using different versions of the `libffi` package (even though systems are incompatible with builds made with different versions):
```
realvarx@rs-2022:~/Desktop/at_pico_w/src$ micropython main.py
Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "./lib/atclient.py", line 8, in <module>
  File "./lib/third_party/rsa/__init__.py", line 27, in <module>
  File "./lib/third_party/rsa/key.py", line 572, in <module>
AttributeError: 'module' object has no attribute 'rsa'
realvarx@rs-2022:~/Desktop/at_pico_w/src$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by cpswan** [comment]
@realvarx I've duplicated the error. The latest binaries don't work with my `cpswan-refactor` branch of at_pico_w in exactly the same way that you open this ticket.

```
~/micropython/micropython_1.20.0_3faded33f/micropython main.py
Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "./lib/atclient.py", line 8, in <module>
  File "./lib/third_party/rsa/__init__.py", line 27, in <module>
  File "./lib/third_party/rsa/key.py", line 572, in <module>
AttributeError: 'module' object has no attribute 'rsa'
```

**Comment by cpswan** [comment]
Fixed by https://github.com/atsign-foundation/at_pico_w/pull/18/commits/100f77649280362b94369ed2dcf2bc8bfc28eba5
